
ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.connName=localhost(1414)
ibm.mq.user=admin
ibm.mq.password=password123
management.endpoints.web.exposure.include=metrics,health,prometheus
management.endpoint.metrics.enabled=true
management.observations.enable.messaging=true
management.metrics.enable.messaging=true
management.observations.key-values.messaging.destination=ORDER.REQUEST
management.metrics.export.prometheus.enabled=true
