
ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.host=mqserver
ibm.mq.port=1414
ibm.mq.user=admin
ibm.mq.password=password123

management.endpoints.web.exposure.include=metrics,health,prometheus
management.endpoint.metrics.enabled=true
management.observations.enable.messaging=true
management.metrics.enable.messaging=true
management.observations.key-values.messaging.destination=ORDER.REQUEST
management.metrics.export.prometheus.enabled=true


# Narayana JTA
spring.jta.narayana.enabled=true
spring.jta.transaction-manager-id=order-service-tm

# JMS
spring.jms.template.session.transacted=false
spring.jms.template.session.acknowledge-mode=auto

# Logging (optional but useful to verify XA)
logging.level.com.arjuna=INFO
logging.level.org.springframework.transaction=DEBUG
