ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.connName=localhost(1414)

ibm.mq.user=admin
ibm.mq.password=password123

ibm.mq.sslCipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
ibm.mq.ssl-bundle=mqclient


# Truststore (To verify the MQ Server)
spring.ssl.bundle.jks.mqclient.truststore.location=classpath:client-truststore.p12
spring.ssl.bundle.jks.mqclient.truststore.password=password

# Keystore (To identify the Java App to MQ) - ADD THIS
spring.ssl.bundle.jks.mqclient.keystore.location=classpath:client-truststore.p12
spring.ssl.bundle.jks.mqclient.keystore.password=password

#spring.ssl.bundle.jks.mqclient.truststore.type=PKCS12